package com.psionline.selt.booking;

// Generated by Selenium IDE
import org.junit.After;
import org.junit.Before;
import org.junit.Ignore;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

@Ignore
public class BookActivityA1TimedoutTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver", "./drivers/win32/chromedriver.exe");
        System.setProperty("webdriver.chrome.logfile", "./chromedriver.log");
        System.setProperty("webdriver.chrome.verboseLogging", "true");
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void bookActivityA1Timedout() {
        driver.get("http://localhost:8086/");
        driver.manage().window().setSize(new Dimension(1007, 660));
        driver.findElement(By.id("startYourBooking")).click();
        driver.findElement(By.id("username")).click();
        driver.findElement(By.id("password")).sendKeys("Fatfr@g99");
        driver.findElement(By.id("username")).sendKeys("gypsy@test.com");
        driver.findElement(By.name("login")).click();
        driver.findElement(By.id("book-new-test")).click();
        driver.findElement(By.id("proceed")).click();
        driver.findElement(By.id("activity-options")).click();
        {
            WebElement dropdown = driver.findElement(By.id("activity-options"));
            dropdown.findElement(By.xpath("//option[. = 'UKVI Speaking and listening at level A1']")).click();
        }
        driver.findElement(By.id("activity-options")).click();
        driver.findElement(By.id("proceed")).click();
        driver.findElement(By.id("countries")).click();
        {
            WebElement dropdown = driver.findElement(By.id("countries"));
            dropdown.findElement(By.xpath("//option[. = 'Afghanistan']")).click();
        }
        driver.findElement(By.id("countries")).click();
        driver.findElement(By.id("location")).click();
        driver.findElement(By.id("ui-id-2")).click();
        driver.findElement(By.id("location")).sendKeys("Kabul, Afghanistan");
        driver.findElement(By.cssSelector(".glyphicon")).click();
        js.executeScript("window.scrollTo(0,8.333333015441895)");
        js.executeScript("window.scrollTo(0,133.3333282470703)");
        driver.findElement(By.id("1")).click();
        driver.findElement(By.cssSelector("#no8 > .day-number")).click();
        driver.findElement(By.id("day8-book0")).click();
        driver.findElement(By.id("proceed")).click();
        driver.findElement(By.id("authorise")).click();
        driver.findElement(By.id("proceed")).click();
        driver.close();
    }
}
