// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Book Activity A1 Timed-out', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Book Activity A1 Timed-out', async function() {
    // Test name: Book Activity A1 Timed-out
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:8086/")
    // 2 | setWindowSize | 1007x660 | 
    await driver.manage().window().setRect(1007, 660)
    // 3 | click | id=startYourBooking | 
    await driver.findElement(By.id("startYourBooking")).click()
    // 4 | click | id=username | 
    await driver.findElement(By.id("username")).click()
    // 5 | type | id=password | Fatfr@g99
    await driver.findElement(By.id("password")).sendKeys("Fatfr@g99")
    // 6 | type | id=username | gypsy@test.com
    await driver.findElement(By.id("username")).sendKeys("gypsy@test.com")
    // 7 | click | name=login | 
    await driver.findElement(By.name("login")).click()
    // 8 | click | id=book-new-test | 
    await driver.findElement(By.id("book-new-test")).click()
    // 9 | click | id=proceed | 
    await driver.findElement(By.id("proceed")).click()
    // 10 | click | id=activity-options | 
    await driver.findElement(By.id("activity-options")).click()
    // 11 | select | id=activity-options | label=UKVI Speaking and listening at level A1
    {
      const dropdown = await driver.findElement(By.id("activity-options"))
      await dropdown.findElement(By.xpath("//option[. = 'UKVI Speaking and listening at level A1']")).click()
    }
    // 12 | click | id=activity-options | 
    await driver.findElement(By.id("activity-options")).click()
    // 13 | click | id=proceed | 
    await driver.findElement(By.id("proceed")).click()
    // 14 | click | id=countries | 
    await driver.findElement(By.id("countries")).click()
    // 15 | select | id=countries | label=Afghanistan
    {
      const dropdown = await driver.findElement(By.id("countries"))
      await dropdown.findElement(By.xpath("//option[. = 'Afghanistan']")).click()
    }
    // 16 | click | id=countries | 
    await driver.findElement(By.id("countries")).click()
    // 17 | click | id=location | 
    await driver.findElement(By.id("location")).click()
    // 18 | click | id=ui-id-2 | 
    await driver.findElement(By.id("ui-id-2")).click()
    // 19 | type | id=location | Kabul, Afghanistan
    await driver.findElement(By.id("location")).sendKeys("Kabul, Afghanistan")
    // 20 | click | css=.glyphicon | 
    await driver.findElement(By.css(".glyphicon")).click()
    // 21 | runScript | window.scrollTo(0,8.333333015441895) | 
    await driver.executeScript("window.scrollTo(0,8.333333015441895)")
    // 22 | runScript | window.scrollTo(0,133.3333282470703) | 
    await driver.executeScript("window.scrollTo(0,133.3333282470703)")
    // 23 | click | id=1 | 
    await driver.findElement(By.id("1")).click()
    // 24 | click | css=#no8 > .day-number | 
    await driver.findElement(By.css("#no8 > .day-number")).click()
    // 25 | click | id=day8-book0 | 
    await driver.findElement(By.id("day8-book0")).click()
    // 26 | click | id=proceed | 
    await driver.findElement(By.id("proceed")).click()
    // 27 | click | id=authorise | 
    await driver.findElement(By.id("authorise")).click()
    // 28 | click | id=proceed | 
    await driver.findElement(By.id("proceed")).click()
    // 29 | close |  | 
    await driver.close()
  })
})
