package com.psionline.selt.booking;

import org.junit.After;
import org.junit.Before;
// Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.Select;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class BookC2andCancel1Test {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver", "./drivers/win32/chromedriver.exe");
        System.setProperty("webdriver.chrome.logfile", "./chromedriver.log");
        System.setProperty("webdriver.chrome.verboseLogging", "true");
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();

    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void bookC2andCancel1() {
        // Test name: Book C2 and Cancel (1)
        // Step # | name | target | value
        // 1 | open | http://localhost:8086/ |
        driver.get("http://localhost:8086/");
        // 2 | setWindowSize | 1296x696 |
        driver.manage().window().setSize(new Dimension(1296, 696));
        // 3 | click | id=startYourBooking |
        driver.findElement(By.id("startYourBooking")).click();
        // 4 | click | id=username |
        driver.findElement(By.id("username")).click();
        // 5 | type | id=password | Fatfr@g99
        driver.findElement(By.id("password")).sendKeys("Fatfr@g99");
        // 6 | type | id=username | gypsy@test.com
        driver.findElement(By.id("username")).sendKeys("gypsy@test.com");
        // 7 | click | name=login |
        driver.findElement(By.name("login")).click();
        // 8 | click | id=book-new-test |
        driver.findElement(By.id("book-new-test")).click();
        // 9 | click | id=proceed |
        driver.findElement(By.id("proceed")).click();
        // 10 | click | id=activity-options |
        driver.findElement(By.id("activity-options")).click();
        // 11 | select | id=activity-options | label=UKVI Speaking, listening, reading, and writing at level C2
        // label=UKVI Speaking, listening, reading, and writing at level C2
        {
//            WebElement dropdown = driver.findElement(By.id("activity-options"));
//            dropdown.findElement(By.xpath("//option[. = 'UKVI Speaking, listening, reading, and writing at level C2']"))
//            .click();
            Select dropdown = new Select(driver.findElement(By.id("activity-options")));
            dropdown.selectByVisibleText("UKVI Speaking, listening, reading, and writing at level C2");
        }
        // 12 | click | id=activity-options |
        driver.findElement(By.id("activity-options")).click();
        // 13 | click | id=proceed |
        driver.findElement(By.id("proceed")).click();
        // 14 | click | id=countries |
        driver.findElement(By.id("countries")).click();
        // 15 | select | id=countries | label=Afghanistan
        {
            WebElement dropdown = driver.findElement(By.id("countries"));
            dropdown.findElement(By.xpath("//option[. = 'Afghanistan']")).click();
        }
        // 16 | click | id=countries |
        driver.findElement(By.id("countries")).click();
        // 17 | click | id=location |
        driver.findElement(By.id("location")).click();
        // 19 | type | id=location | Kabul, Afghanistan
        driver.findElement(By.id("location")).sendKeys("Kabul, Afghanistan");
        // 20 | click | id=_eventId_search |
        driver.findElement(By.id("_eventId_search")).click();
        // 21 | click | id=1 |
        driver.findElement(By.id("1")).click();
        // 22 | click | id=no3 |
//        driver.findElement(By.id("no3")).click();
        List<WebElement> days = driver.findElements(By.cssSelector(".othercentre"));
        days.get(0).click();
        // 23 | click | id=day3-book0 |
//        driver.findElement(By.id("day3-book0")).click();
        driver.findElement(By.partialLinkText("Book Test")).click();
        // 24 | click | id=proceed |
        driver.findElement(By.id("proceed")).click();
        // 25 | click | id=authorise |
        driver.findElement(By.id("authorise")).click();
        // 26 | waitForElementVisible | xpath=//h1[contains(.,'Thank you')] | 30000
        // Wait for payment
        {
            WebDriverWait wait = new WebDriverWait(driver, 30);
            wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//h1[contains(.,\'Thank you\')]")));
        }
        // DB update pause.
        try {
            Thread.currentThread().sleep(3000);
        } catch (InterruptedException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        // 27 | click | id=my-account |
        driver.findElement(By.id("my-account")).click();
        // 28 | click | linkText=Confirmed bookings 1 |
        driver.findElement(By.linkText("Confirmed bookings 1")).click();
        // 29 | click | id=confirmed-1-okbutton |
        driver.findElement(By.id("confirmed-1-okbutton")).click();
        // 30 | click | id=confirmCancel |
        driver.findElement(By.id("confirmCancel")).click();
        // 31 | click | id=cancel |
        driver.findElement(By.id("cancel")).click();
        // 32 | click | id=logout |
        driver.findElement(By.id("logout")).click();
    }
}
