package com.psionline.selt.booking;

import org.junit.After;
import org.junit.Before;
import org.junit.Ignore;
// Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.HashMap;
import java.util.Map;

@Ignore
public class BookActivityA1TimedoutGridTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() throws MalformedURLException {
        driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"),
                /* DesiredCapabilities.chrome() */new DesiredCapabilities());
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void bookActivityA1Timedout() {
    // Test name: Book Activity A1 Timed-out
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://localhost:8086/");
    // 2 | setWindowSize | 1007x660 | 
    driver.manage().window().setSize(new Dimension(1007, 660));
    // 3 | click | id=startYourBooking | 
    driver.findElement(By.id("startYourBooking")).click();
    // 4 | click | id=username | 
    driver.findElement(By.id("username")).click();
    // 5 | type | id=password | Fatfr@g99
    driver.findElement(By.id("password")).sendKeys("Fatfr@g99");
    // 6 | type | id=username | gypsy@test.com
    driver.findElement(By.id("username")).sendKeys("gypsy@test.com");
    // 7 | click | name=login | 
    driver.findElement(By.name("login")).click();
    // 8 | click | id=book-new-test | 
    driver.findElement(By.id("book-new-test")).click();
    // 9 | click | id=proceed | 
    driver.findElement(By.id("proceed")).click();
    // 10 | click | id=activity-options | 
    driver.findElement(By.id("activity-options")).click();
    // 11 | select | id=activity-options | label=UKVI Speaking and listening at level A1
    {
      WebElement dropdown = driver.findElement(By.id("activity-options"));
      dropdown.findElement(By.xpath("//option[. = 'UKVI Speaking and listening at level A1']")).click();
    }
    // 12 | click | id=activity-options | 
    driver.findElement(By.id("activity-options")).click();
    // 13 | click | id=proceed | 
    driver.findElement(By.id("proceed")).click();
    // 14 | click | id=countries | 
    driver.findElement(By.id("countries")).click();
    // 15 | select | id=countries | label=Afghanistan
    {
      WebElement dropdown = driver.findElement(By.id("countries"));
      dropdown.findElement(By.xpath("//option[. = 'Afghanistan']")).click();
    }
    // 16 | click | id=countries | 
    driver.findElement(By.id("countries")).click();
    // 17 | click | id=location | 
    driver.findElement(By.id("location")).click();
    // 18 | click | id=ui-id-2 | 
    driver.findElement(By.id("ui-id-2")).click();
    // 19 | type | id=location | Kabul, Afghanistan
    driver.findElement(By.id("location")).sendKeys("Kabul, Afghanistan");
    // 20 | click | css=.glyphicon | 
    driver.findElement(By.cssSelector(".glyphicon")).click();
    // 21 | runScript | window.scrollTo(0,8.333333015441895) | 
    js.executeScript("window.scrollTo(0,8.333333015441895)");
    // 22 | runScript | window.scrollTo(0,133.3333282470703) | 
    js.executeScript("window.scrollTo(0,133.3333282470703)");
    // 23 | click | id=1 | 
    driver.findElement(By.id("1")).click();
    // 24 | click | css=#no8 > .day-number | 
    driver.findElement(By.cssSelector("#no8 > .day-number")).click();
    // 25 | click | id=day8-book0 | 
    driver.findElement(By.id("day8-book0")).click();
    // 26 | click | id=proceed | 
    driver.findElement(By.id("proceed")).click();
    // 27 | click | id=authorise | 
    driver.findElement(By.id("authorise")).click();
    // 28 | click | id=proceed | 
    driver.findElement(By.id("proceed")).click();
    // 29 | close |  | 
    driver.close();
  }
}
