// Generated by Selenium IDE
package com.psionline.selt.booking;

import org.junit.After;
import org.junit.Before;
import org.junit.Ignore;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

@Ignore
public class CancelC2ActivityTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void cancelC2Test() {
        // Test name: Cancel C2 Test
        // Step # | name | target | value
        // 1 | open | http://localhost:8086/manage-account |
        driver.get("http://localhost:8086/manage-account");
        // 2 | setWindowSize | 1280x564 |
        driver.manage().window().setSize(new Dimension(1280, 564));
        // 3 | click | linkText=Confirmed bookings 1 |
        driver.findElement(By.partialLinkText("Confirmed bookings")).click();
        // 4 | click | id=confirmed-1-okbutton |
        driver.findElement(By.id("confirmed-1-okbutton")).click();
        // 5 | click | id=confirmCancel |
        driver.findElement(By.id("confirmCancel")).click();
        // 6 | click | id=cancel |
        driver.findElement(By.id("cancel")).click();
        // 7 | click | linkText=Confirmed bookings 0 |
        driver.findElement(By.partialLinkText("Confirmed bookings")).click();
    }
}
