# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCancelC2Test():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_cancelC2Test(self):
    self.driver.get("http://localhost:8086/manage-account")
    self.driver.set_window_size(1280, 564)
    self.driver.find_element(By.LINK_TEXT, "Confirmed bookings 1").click()
    self.driver.find_element(By.ID, "confirmed-1-okbutton").click()
    self.driver.find_element(By.ID, "confirmCancel").click()
    self.driver.find_element(By.ID, "cancel").click()
    self.driver.find_element(By.LINK_TEXT, "Confirmed bookings 0").click()
  
